// <auto-generated />
using ChessStudySystem.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChessStudySystem.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250731221358_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("ChessStudySystem.Web.Models.Opening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Eco")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fen")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEcoRoot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Moves")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scid")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Src")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Eco");

                    b.HasIndex("Fen");

                    b.HasIndex("Name");

                    b.ToTable("Openings");
                });
#pragma warning restore 612, 618
        }
    }
}
